# PostgreSQL. Versions 9.3 and up are supported.
#
# Configure Using Gemfile
# gem "pg"
#
default: &default
  adapter: postgresql
  encoding: UTF8
  username: <%= ENV.fetch("POSTGRES_USER") { 'postgres' } %>
  password: <%= File.read('/run/secrets/db_password').strip if File.exist?('/run/secrets/db_password') { 'mypassword' } %>
  host: <%= ENV.fetch("POSTGRES_HOST") { 'db' } %>
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: pokemon
